{% set version = "2019.03.09" %}
{% set name = "certifi" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/JohnAdders/python-{{ name }}/archive/{{ version }}.tar.gz
  sha256: fc86808d8c4d6f63ce4932b2fc17198b36622a68ade49eb0e2b14a88674e2f85
 
build:
  number: 1000
  preserve_egg_dir: True
  script: python setup.py install

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - certifi

about:
  home: http://certifi.io/
  license: ISC
  license_file: LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
  description: |
   Certifi is a curated collection of Root Certificates for validating the
   trustworthiness of SSL certificates while verifying the identity of TLS
   hosts.
  doc_url: https://pypi.python.org/pypi/certifi
  dev_url: https://github.com/JohnAdders/python-certifi
  doc_source_url: https://github.com/certifi/certifi.io/blob/master/README.rst

extra:
  recipe-maintainers:
    - johnad
