compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'

provider:
  linux: travis
  osx: travis
  win: appveyor

travis:
  secure:
    BINSTAR_TOKEN: MwSkpVAezOWFH0pYKQY9OcqsZL59xHgvk3Q7JKCBF6m/0f7mvlcPmS9U3TVARKGefHYuDk8xWV/DtNVTX9UXuHWYBJQh2dAgu5bJRN5C+IiT1sx9i0cftaaSI1A5rAonXltllB5o0bsJSlVSgod2yhuqrVP2Xppzx6EDbVQCDPqlXykbKYf/RLcteAa4HMkC47sx5oYjSK4OLhPzA8SbOjEuqtVsk5CgCiokNd9oFwDbXVHwaAoNRS4gHACv4voie68RokvBGa/48GLqxR/d/ksBusGzGJ5VVrnXpRlhjCnsxv3ia1f+of/cNaTFZwj7fY3ty7Vu0l7P7GrX2Gla/Yckds3poXYjwHSV3DWlI0kzTR6mkC23efnAjZLkDc+7GBoIyhnELjW8BJF3dzlXwJDHR5ZYlW6C8oy0W9urhuaZnW2DEiAdhkE6pAunRQTxg+GCb9WQnUINx24jXWEYMa6lcmDUMsEqEdkdx0n77yrErX2MW9pZvbZzy0hGgvivtejr3N/Xqw11uyxOgjuGzKAPts30i40Q6fdt2W5pLzd4kokAPdtwwy90nvWuvoAP0LSSCFvNxe34yey/VsCHTDK9H2NgkhBAMjbo4+cOOgJUpcztjq4WILTrZ8Ql4qTWuycxEUkjGKQh4IgnN7c2hzfrdvofN6vBKbJe2WPLUIM=
