channels:
  # Needed for appveyor
  sources:
  - johnad
  - conda-forge
  - defaults
  # Needed for readme generation
  targets:
  - [johnad, main]

# Needed for ci_support
channel_sources:
- johnad,conda-forge,defaults

# Needed for ci_support
channel_targets:
- johnad main

# Needed for something else
github:
  user_or_org: JohnAdders
  branch_name: master

compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'

provider:
  linux: circle
  osx: travis
  win: appveyor

travis:
  secure:
    BINSTAR_TOKEN: D4Ym7Reo6kgXKaVjET22c6nbQgLGCB2fGjJ7x1wPhlKKNIuZLANCb387S9c846xZIPlSQTWnp4l4Dfl5ghWb0yf01W9dXKivy9RuH+riNR0LTmmgvleHDV4HEKZwtFItBxarNSLuVwA88JnaEkLDHn3jwPSJhVtHjCH/hbqr55iztWFgciPD8a/jJgVE1Y6uSlXBSn2adzqucp22UZSOLSgUj8zZ/m75b3aGoy0ZztHOYg8mwhq7/zKT7Qv4dWIq5wy0/VW7n/Qv5Ncghd7Khk5tKFeRCidl2biiFQhY8D0KtBATATQpge5EWGysIO8q0RsOGdIMAU1WjDDP2BeMM+HshnKb0gVau0CdKHN6d8eiHNLisIH9u1Fqrqqoy8y9/XXES08KTVmOJTo7kZtoM87/C2f+kNPpcetHOv8fbpn8LDRNq6oAoczh9VtBopyqKbPBKEOYfqHpNzfyKzYVTTHEYxp1mHC4T0f24122Z+3ulgh/dIitGAfNLZXLMxf6XnGRIh22A5pgy7JCWT6AMN0BzWpGaarJCSUxHMuD0vRQhh0uCv7Kvph+NW8iFoHoTyPqtSHKIj28a16Jo/9J5kCuUyqlERQEtmfZ81nnurRC+E+Fm9Ycj85gPUaH8CM3QpCIxs46ORyGpz6EgaySucaEDlUItgaNk1P+3McTJX0=

appveyor:
  secure:
    BINSTAR_TOKEN: p6dounPSHKjzsxDW9x0GKMMjWaN9yPMAzEh+CFeTcPSAwEknTcgwrRjGX7MM1B0p
