github:
  user_or_org: JohnAdders
travis:
  secure:
    BINSTAR_TOKEN: J7F587cSAl5P8EgPFVonnNn36SBIsuIpcDIp54lY1Xx1aqbacEQWNxgpKhX6rg2Ohq7aR5q0exYmOSnY/rpdyJ9hak9w0k3mW0X7I1Ids8/n3GgYdUxxp74QKbmS8KQnZP+3whIdL9u2ZayHwpG0WogdeEIi/Pj/lG4DtwKW4ODt5bdiZw4Xp/3QVL5inBzrMxd5+RKodhLrtqq14n8hfXm7KtZ7tiFeuAy9T8dLbKOR+Y96HVMjoVyKtDYgRH0RDj2W/ZxF6mMqQhVYqTOzoPOKBPGeWn/V6klNvvL0N27uTrs4X0WAe3KfDa3TCXVWnbZEDUlcJPC0PLgFEVh16Hq6RXUnpqiE4qt9RjU0BR7HwH8pGQSBa3by9y6aX4IyuPEpUWzsYkd6mpIsVsQ8D5pnf6q/Zsl+CpDoOQBtgptbgpC/wggDlCGA5ORv4c75fz+P4xft5qFEanrNZKpIPlheKfjxkhpMxp63vCMMIm1Z7LLu0Ygpen2I8EYQGV7llnuBB8eYnFV0p3b3xe6NvlhNVp/15kVXqWdIsX0VSPds1/78Y2KbRx0D4jWOdH+zR8y3iWv8ze/MD5lbvRatOID0uL445bNkjAqs685dh01N+np3mnXwH74NoH4PjFm3xrAQKoMbCL7fIYhhNW6iB87okXYM/bpzvXkT29sSixg=
appveyor:
  secure:
    BINSTAR_TOKEN: p6dounPSHKjzsxDW9x0GKMMjWaN9yPMAzEh+CFeTcPSAwEknTcgwrRjGX7MM1B0p
